# Generated by Django 6.0.1 on 2026-01-20 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adm',
            name='can_edit_about',
        ),
        migrations.RemoveField(
            model_name='adm',
            name='can_edit_contact',
        ),
        migrations.RemoveField(
            model_name='adm',
            name='can_view_students',
        ),
        migrations.AddField(
            model_name='adm',
            name='priv',
            field=models.CharField(default='', max_length=100),
        ),
    ]
