# Generated by Django 6.0.1 on 2026-02-15 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_course_teacher_batch_enrollment_resource'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='dept',
        ),
        migrations.RemoveField(
            model_name='student',
            name='roll',
        ),
    ]
