# Generated by Django 6.0.1 on 2026-02-15 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_student_dept_remove_student_roll'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to='receipts/'),
        ),
    ]
