# Generated by Django 6.0.1 on 2026-02-15 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_enrollment_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='subject_code',
            field=models.CharField(default=101, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
