# Generated by Django 6.0.1 on 2026-02-15 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_course_subject_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='schedule_days',
            field=models.CharField(default=2, help_text='e.g. Mon, Wed, Fri', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='batch',
            name='schedule_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
