# Generated by Django 6.0.1 on 2026-02-15 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_officialreceipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='class_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
