# Generated by Django 6.0.1 on 2026-02-15 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_batch_class_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='class_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
