# Generated by Django 6.0.1 on 2026-02-15 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_batch_class_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='is_halted',
            field=models.BooleanField(default=False),
        ),
    ]
