# Generated by Django 6.0.1 on 2026-02-16 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_course_is_free'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
