# Generated by Django 6.0.1 on 2026-02-21 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_assignmentsubmission_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='course_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='course_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
