# Generated by Django 6.0.1 on 2026-02-22 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_enrollment_course_feedback_enrollment_course_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='completion_requested',
            field=models.BooleanField(default=False),
        ),
    ]
