# Generated by Django 6.0.1 on 2026-02-23 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_doubt_doubtreply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doubtreply',
            old_name='answer',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='doubtreply',
            old_name='user_role',
            new_name='replied_by_role',
        ),
        migrations.AddField(
            model_name='doubtreply',
            name='replied_by_name',
            field=models.CharField(default='System', max_length=100),
        ),
        migrations.CreateModel(
            name='StudentDoubt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='doubts/')),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.batch')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.enrollment')),
            ],
        ),
        migrations.AlterField(
            model_name='doubtreply',
            name='doubt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='app.studentdoubt'),
        ),
        migrations.DeleteModel(
            name='Doubt',
        ),
    ]
