# Generated by Django 6.0.1 on 2026-02-23 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_rename_answer_doubtreply_message_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentdoubt',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='doubtreply',
            name='replied_by_name',
            field=models.CharField(max_length=100),
        ),
    ]
